"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-30

Hand-written rather than autogenerated (no live Postgres instance was
reachable in this environment to diff against). This mirrors every model
in app/models/ exactly as of this commit. Tables are created in FK-safe
order: independent tables first, then tables that reference them.

After this migration is stamped as the baseline, all future schema
changes should go through `alembic revision --autogenerate -m "..."`
against a real database connection so Alembic can diff properly — do not
hand-write migrations after this one unless autogenerate is unavailable.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True, index=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("name", sa.String(100)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("age", sa.Integer()),
        sa.Column("occupation", sa.String(100)),
        sa.Column("work_start_time", sa.Time()),
        sa.Column("work_end_time", sa.Time()),
        sa.Column("work_days", sa.JSON()),
        sa.Column("commute_time_minutes", sa.Integer(), server_default="30"),
        sa.Column("sports", sa.JSON()),
        sa.Column("hobbies", sa.JSON()),
        sa.Column("skills_learning", sa.JSON()),
        sa.Column("long_term_goals", sa.JSON()),
        sa.Column("fitness_info", sa.JSON()),
        sa.Column("diet_tracking", sa.JSON()),
        sa.Column("sleep_target_hours", sa.DECIMAL(3, 1), server_default="8.0"),
        sa.Column("bedtime", sa.Time()),
        sa.Column("wake_time", sa.Time()),
        sa.Column("has_part_time_job", sa.Boolean(), server_default=sa.false()),
        sa.Column("part_time_start", sa.Time()),
        sa.Column("part_time_end", sa.Time()),
        sa.Column("part_time_days", sa.JSON()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "fixed_events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("day_of_week", sa.SmallInteger()),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("start_date", sa.Date()),
        sa.Column("end_date", sa.Date()),
        sa.Column("is_recurring", sa.Boolean(), server_default=sa.false()),
        sa.Column("recurrence_rule", sa.String(255)),
        sa.Column("category", sa.Enum("college", "work", "part_time", "appointment", "other", name="event_category"), nullable=False, server_default="other"),
        sa.Column("color", sa.String(7), server_default="#3788d8"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("priority", sa.SmallInteger(), nullable=False, server_default="3"),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False, server_default="30"),
        sa.Column("category", sa.Enum("hobby", "skill", "fitness", "career", "health", "academic", "chore", "other", name="task_category"), nullable=False, server_default="other"),
        sa.Column("due_date", sa.Date()),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.false()),
        sa.Column("is_recurring", sa.Boolean(), server_default=sa.false()),
        sa.Column("recurrence_rule", sa.String(255)),
        sa.Column("is_flexible", sa.Boolean(), server_default=sa.true()),
        sa.Column("preferred_time_slot", sa.Enum("morning", "afternoon", "evening", "any", name="time_slot"), server_default="any"),
        sa.Column("min_times_per_week", sa.Integer()),
        sa.Column("parent_goal_id", sa.Integer(), sa.ForeignKey("tasks.id", ondelete="SET NULL")),
        sa.Column("progress", sa.DECIMAL(5, 2), server_default="0.00"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "habits",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("unit", sa.String(50)),
        sa.Column("target_value", sa.DECIMAL(10, 2)),
        sa.Column("frequency", sa.Enum("daily", "weekly", "per_meal", name="habit_frequency"), nullable=False, server_default="daily"),
        sa.Column("icon", sa.String(50)),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "habit_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("habit_id", sa.Integer(), sa.ForeignKey("habits.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("value", sa.DECIMAL(10, 2)),
        sa.Column("notes", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("habit_id", "log_date", name="uq_habit_log"),
    )

    op.create_table(
        "daily_schedules",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("schedule_date", sa.Date(), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), server_default=sa.false()),
        sa.Column("total_free_hours", sa.DECIMAL(4, 1)),
        sa.Column("total_scheduled_hours", sa.DECIMAL(4, 1)),
        sa.Column("is_balanced", sa.Boolean()),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("user_id", "schedule_date", name="uq_daily_schedule"),
    )

    op.create_table(
        "schedule_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("schedule_id", sa.Integer(), sa.ForeignKey("daily_schedules.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.Enum("fixed_event", "task", "habit", "break", "meal", "travel", "sleep", "bath", "free", "gym", name="item_type"), nullable=False),
        sa.Column("task_id", sa.Integer(), sa.ForeignKey("tasks.id", ondelete="SET NULL")),
        sa.Column("event_id", sa.Integer(), sa.ForeignKey("fixed_events.id", ondelete="SET NULL")),
        sa.Column("habit_id", sa.Integer(), sa.ForeignKey("habits.id", ondelete="SET NULL")),
        sa.Column("status", sa.Enum("scheduled", "completed", "missed", "rescheduled", name="item_status"), nullable=False, server_default="scheduled"),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("priority_at_schedule", sa.SmallInteger()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "rescheduled_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("schedule_item_id", sa.Integer(), sa.ForeignKey("schedule_items.id", ondelete="CASCADE"), nullable=False),
        sa.Column("original_date", sa.Date(), nullable=False),
        sa.Column("rescheduled_to_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Enum("not_completed", "conflict", "user_request", name="reschedule_reason"), nullable=False, server_default="not_completed"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "end_of_day_checklists",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("checklist_date", sa.Date(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.false()),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("user_id", "checklist_date", name="uq_checklist"),
    )

    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("checklist_id", sa.Integer(), sa.ForeignKey("end_of_day_checklists.id", ondelete="CASCADE"), nullable=False),
        sa.Column("schedule_item_id", sa.Integer(), sa.ForeignKey("schedule_items.id", ondelete="SET NULL")),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("is_checked", sa.Boolean(), server_default=sa.false()),
        sa.Column("checked_at", sa.DateTime(timezone=True)),
    )

    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("schedule_item_id", sa.Integer(), sa.ForeignKey("schedule_items.id", ondelete="CASCADE")),
        sa.Column("reminder_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_sent", sa.Boolean(), server_default=sa.false()),
        sa.Column("sent_at", sa.DateTime(timezone=True)),
        sa.Column("type", sa.Enum("pre_task", "bedtime", "habit", "daily_review", "wake_up", name="reminder_type"), nullable=False, server_default="pre_task"),
    )

    op.create_table(
        "google_calendar_sync",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("access_token", sa.Text()),
        sa.Column("refresh_token", sa.Text()),
        sa.Column("token_expiry", sa.DateTime(timezone=True)),
        sa.Column("google_calendar_id", sa.String(255), server_default="primary"),
        sa.Column("last_synced_at", sa.DateTime(timezone=True)),
        sa.Column("sync_enabled", sa.Boolean(), server_default=sa.true()),
    )

    op.create_table(
        "user_devices",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("fcm_token", sa.String(500), nullable=False),
        sa.Column("platform", sa.String(20), server_default="android"),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    # Reverse FK-dependency order
    op.drop_table("user_devices")
    op.drop_table("google_calendar_sync")
    op.drop_table("reminders")
    op.drop_table("checklist_items")
    op.drop_table("end_of_day_checklists")
    op.drop_table("rescheduled_items")
    op.drop_table("schedule_items")
    op.drop_table("daily_schedules")
    op.drop_table("habit_logs")
    op.drop_table("habits")
    op.drop_table("tasks")
    op.drop_table("fixed_events")
    op.drop_table("user_profiles")
    op.drop_table("users")

    # Drop enum types explicitly (Postgres doesn't auto-drop these with the table)
    for enum_name in [
        "event_category", "task_category", "time_slot", "habit_frequency",
        "item_type", "item_status", "reschedule_reason", "reminder_type",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
